create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  occurred_at timestamptz not null default now(),
  user_id uuid null,
  anonymous_id text not null,
  session_id text not null,
  page_name text not null,
  path text not null,
  event_name text not null,
  properties jsonb not null default '{}'::jsonb
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_user_id_idx
  on public.analytics_events (user_id);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

alter table public.analytics_events enable row level security;

drop policy if exists "analytics_insert_anon_or_self" on public.analytics_events;
create policy "analytics_insert_anon_or_self"
on public.analytics_events
for insert
to anon, authenticated
with check (
  user_id is null or auth.uid() = user_id
);

grant insert on public.analytics_events to anon, authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;
